spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 200101314520
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8090
